language: java
jdk:
- oraclejdk8
deploy:
  provider: bintray
  key:
    secure: C23iuKHNF/i9jzrhz3Hi3t1xSO3Yz+qaauNoRHSPnrlaf35hWjpfzgoxZnOpTSA0/WF2Pq4AzQd21FBlm5K9jw8Y5hSYuZYaXNwanzY7VaNLhQSJupsuLFvIswk5KfArJqZWP2nnF2ghly+Kzw6AQIsLRDzkurMx6gBpyAUxzD8dyJLezkaV9oFJAt2BaqonVHx6582I73ULuVcUHUSoCj4xVMD8jTYLaZjpze6b/bSbQ7/v0LpNId/iIdatcN02fHq/jBznntPk3/TjpA26FHkXgvBz3yi4dGHsMchLxVPOo5FUMqULQlBh9cGfVHvHDR6hdhY1KUdYHVhz2Ys1F+LaqLPNVW48IHa9xtWy3O4DeV+hQZ8Fgz5gnhI9BHBrsXupLbZ2Gb5RNQOPiPvXqBJd9NnXvFFsiItTOGc+Rbu3bjb1bI66jMmTIHyyp73OLFwRcR4Gah4b80PDQlq5pvJVFv5gyKrus9WZdCB+d4V8lPvuCCkQowqewAYbnJwpWzGmsqGllVDVV/3gxcicldnwCbIG05cGcYAbkkIhvBkakHRlnHSg532mxWzAFt8IrIhZmLbiw6+nVUG9GaKmQ+1KR5VKdBQLoDJ5BBYJIk5Cvyt0KT0TY5dChFoBSJVdBbcmdinLIRmjOZDhrCHsxVbFENJubJDLOqcZv2ZK3j8=
  file: "descriptor.json"
  user: "abstratt"
