dist: trusty
language: java
jdk:
- oraclejdk8
install:
  mvn clean deploy --settings deploy.settings.xml -DdeployAtEnd=true
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
  - secure: "TKsjuiqA2hpqf93TYlp/6vS8aOB0oFEvJ9nDzgcpTg5UFbCTmRPCOEyQeKj1FCYR+sfccFCiicANy1TR31aqPNh5szJ85kkvf2SmosYUO8JPZk+l2QWdykAx1EallFC8SfGvWLA+mn6HPhbA2Yw46+u59jrvLsVpek+/2PNL9fN4G7yKlIRX2S9IyZ9P6HG10qEmreUUF3oYRDHaoMuPm+6Bvd82CZxkE2/cDA/Iq8s3M8oXBLuOw1cfOzbhjMLE+Ng1kr3ZO8fj5CcnV1aA+xYpQFrnIOZZL8Z/Axv1Uc+0jxud1ikqU3ijiZUAuaMTsKD32o3RJzOi3AjSmeUUKxd24DL0lJsdBlsK5JMnJ8cVzLPks1CKiv4gqv47ugZIFrAqR41NroOAU8ocUnjXxvtg7oKsGRonY15VVYn9xOgLzn8ovsv0Z54AD7/OhOTVgH+qCNttNnHEE30DD+ulO74qUrdURg4gUql9YYKumKLuXZpuHNTH665J5S0h4UtB61cJOmWmDzpLnGxseZ6d7Cmz/2mEyPELl7cp2P3qY70CENhRo6AWAku0c76ggP5YGXu6KuLu1EdxkP+/iU5QZ00kdsrawvOpbsdd1TxijOLU977TeOfeUBqwWMIkdi1yvJUEdNcPIwcxQfxZrVRMXuU3qmedywHuJMZJcpwZGk4="
  - secure: "DLt05HZX+30Q5euZYC+TvVb3SG0OtcHQXKov/VziTWvZzxRphD0jOcvygYxfS0mtANvxmH0U8czgqmTX1Nf34cjURL+B7lTtgClsYCNqsI1z91t4K4GuUxpEt+atZqy3eIV1NbHDugmbXFEaIPoZU7Tac3qCuXxJPb+YRNeV0TY85AEMTCN2gMAGbC1Uza6r1eKqZA6PGxKmCqqoAid24xmtgp7ySDwvMNQ7fV1+uHhX7SlNpX4+JbA3xJDW1lUqgz3BSt+qO9m5ypcYRugkQlFdjjVTbMe5cZUwtub7OY4Y2Eh7wo/OVNZj7rxlkkfFZrRJFYoUhiLGLi0mC+FV6dzJKg5TJGr0AZtiXzWYCEn2pIDzJjdLRZLB0z1DSOUvHQBWhiGkTAiTwP73cAPE0t7LM++ZSbrMbn3fkd5Bw2rAGZFdjpgkGiSy4gwk8EgUA7xE9dZiX3Xie2eo1zh8+DtqC/wiNfpr7qBxtGBkHxbceFTbZs03to7XrExWLhJlwDFW+x36mUznye2D0/tlN9acV2DGcmJS+LSGJom4DLBbcy/7Oz/AZEyhIH4MJnAEOoKxKYqaIgW8TUyYI3TXArVABf6ssSyyKjassh1Xl38OMpWew5V7zRXzXZtczjEzuSWuqErkFKMbCDZ3werl12ATOlhjuTM1URcGFVeyYbA=" 

cache:
  directories:
  - $HOME/.m2
