dist: trusty
language: java
jdk:
- oraclejdk8
install: mvn clean deploy --settings deploy.settings.xml -DdeployAtEnd=true
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: QmQm99ZYtPrug2QGFLeyYJyhpF0jY/VQYZTaTqjV3aDhx+tYMCOwP+Exit3Fxca9Uk1yndZSZpE2l6NFhAdFjfJPet2+rnSQ3wqzSkh8jtTBBhuH1MkYMwo6YJ+HdXOzrXeIfv9nwWTkfZVeeJJ/BLDD95Au3oICwZY+LveDJMDxNfDVFxcCkEqWvHdt5BmPfWnSS0wivorYNqI6oSgFZNCBqghikbTz+LLR35Z9kz3BwEv7UYutd9ASEbRLjHS7/w8JuQE4anX56hgm63muXDPS0Soe0dqfGD/z642cinf9yLZYvxfhABvOzrnfhKCyjZpM+OTXTC1O9VVydJXWuUG6B80X/dVESvO3CfdYbhpC6CC610sqe7NjFRV10N05wjB7EUPS8EK0p2A7UUZ9oArfE7RvbF+VDWiv9+d+Wkqq7vqngdvPvR46ZK9bsZHs/Q+avpyZw7/fUpCisbVW14DDk+rQiweMfOP/iSPntniMozEkfUA5/bHb6waZzN2d2QvCfVvMkDkMh0qvP8njbbMe0U4SlyJ5QSXXauljhSwc5J9RaFJY8fVJWy8s45JqlpKGvxIz46V6w7vkHLRUzNS/3ECbJM6ixDaYtLPEaPGzTzuzi/X+Xe3lrySnsWdEEWjvpihhu9Xs9/qlkjjbaOnnOImiQqLdv+gfLZz1beQ=
  - secure: Akw98MuPOa/itR0B5Vybf8r7jCGMwvWRuXunqmkyD7cf2aQ0L+5PXAmweMF56KyllnZmvAz91OjsA2P6StE0iePC3p6fEVyTEH7OxCPnYgVjWbpkY4TkgLdoGRAyTPVOMtBdtZyJ4F6vh5misP2AGnaXQ3xrHvcYwV3eAeXIE1lpZqwoSwzaD4iyGMF7lgMiRSmdMHGPpa+m3xyZFPAYatubA13gLQ3tJBTBHlwXOP+usdjtwtrlFeS+GXl7FeqxYmI809YoAccNMSaitpLcQWf05z89cWifgFmULVReYaJCa5PmnhewqA8DcuBFHXkTEy6plZoA251tt2wHEO4UlyPmvIRqyYoS7P/leB+XGCL2bZUNJBD2L86tCKTqvduNPDRnb1hB0L5IHezH2iTQK8HLcymAvLdUzSWfUZEjG4O1mIemuU7xcA7Z4T2erK3HArvKHQLP1IWaw9J2dfhbqNaZjzvdMaKBxrtXQ3m6g/19N8/MchVQ3lhUiKSXdSmcmdZiyL/6XgK2ovZfdcZm5tYWL0P8yqgT1pfHeqOU7+JkKzf5EcxNSrnesb24gKiJ8JiwA9JbuOWWUS4Ar8vKeD9PvUyZXgLmBaIfEDjDI3Eb+plje/sQZuotebBUC8C4caJjC23vhAn2sHfBlvrhsLI9k7XOq9P4WSKvejogbIk=
