dist: trusty
language: java
jdk:
- oraclejdk8
install: mvn clean deploy --settings deploy.settings.xml -DdeployAtEnd=true
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
deploy:
  key:
    secure: TN1aHzCaZmbpYSf7MspaTdGVlyw5dJ3D7TgXfm6dxrMgvRp7lrukfhFUcbEvUQmfidIm7x9uJjyWA3drR23ylCOACjjCZnc1rws08LoxSy2Nt9fb98SZiIx93Z5jtUu8VAvN2JwI6KqJqGG5nDPyUKypBM+NsyqQ5HdJfNWMUiiFikgflMgIQrzxKQZLYNFKq5Hfak73x9pIXlLKJZP7c1ZphnVpHfes/FfhJmRn610NmmootU+tC3c4WDiM8HhqPioYiSlcbvOmtf/ek7CPZfVLuY4HX31P/ltAnMgNLTf6/VSmQ9Ak1wMGrYpxh7PMAK/AD5byrLJVMm79VBykauZ6iCCe0O++4KIINuOMT9HTC7RHalMhKLTuFUDZtpocrswlINnABjHIDPPJkj1Gxt8q8L/AyQzmukGxui2QGCsFWejBK/a6iscVKSPBqQHWwqV4rglG7DSQIeUDMijJOWx0jCVUh+4ztSQ0lT/BsFjH1bF98A0trdJdym75r8f3yJKEBaFeI4Jb8mR8YHL09XbaIXR0wJfOB0MnVQpRXPRxkXIF5hWseR7bXT3c7My2U9gr4J7F32nAMXirHuOCOP2pY4UWint+bjGpPOGQobplb5V1s33gjK6bgzgu/WLZjuwqvwEknICmCPF/vcNZPbJRjTPjWwp4n//rTLOFkcQ=
